using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessObjects
{
    public class Counters
    {
        //=======================================
        //Contain all autogenerated counters
        //=======================================
        int itemCounter, costumerCounter, orderCounter, lineNo, recieptNo;
        //=======================================
        public int RecieptNo
        {
            get { return recieptNo; }
            set { recieptNo = value; }
        }
        //=======================================
        public int LineNo
        {
            get { return lineNo; }
            set { lineNo = value; }
        }
        //=======================================
        public int OrderCounter
        {
              get { return orderCounter; }
             set { orderCounter = value; }
        }
        //=======================================
        public int CostumerCounter
        {
                get { return costumerCounter; }
                set { costumerCounter = value; }
        }
        //=========================================
        public int ItemCounter
        {
                 get { return itemCounter; }
                 set { itemCounter = value; }
        }
        //==========================================
    }
}
